# Generated by Django 4.2.3 on 2023-08-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='user',
        ),
        migrations.DeleteModel(
            name='WorkspaceSetting',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(upload_to='workspaces/logos/'),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
